# 阿里云OSS对象存储
oss:
  #配置地域节点Endpoint
  endpoint: oss-cn-nanjing.aliyuncs.com
  accessKeyId: LTAI5tLhd4wg31x9gNQj1Ptb
  accessKeySecret: KZWL3WTiEG6P0dz41IyO3C614YIqKE
  bucketName: tracord

server:
  port: 8070
spring:
  application:
    name: tracord_backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tracord?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
