spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tracord?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: LLX20021012
    driver-class-name: com.mysql.cj.jdbc.Driver

# 阿里云OSS对象存储
oss:
  #配置地域节点Endpoint
  endpoint: oss-cn-nanjing.aliyuncs.com
  accessKeyId: LTAI5tLhd4wg31x9gNQj1Ptb
  accessKeySecret: KZWL3WTiEG6P0dz41IyO3C614YIqKE
  bucketName: tracord

